#!/bin/sh
# shellcheck disable=SC1090

##
# If in non interactive shell ( "$-" not containing "i" ),
# execute script as command.
##
if ! { echo "$-" | grep -q i; }; then
# -- Non Interactive ----------------

# If an error occurs, EXIT abnormally.
set -e -o pipefail

##
# constants
##
CONOHA_VERSION='0.0.2'
CONOHA_PROGRAM_NAME="$(basename -- "$0")"



##
# common
##
PrintStderr() {
  echo "$*" | sed "s|$HOME|\$HOME|g" 1>&2
}

CheckDependency() {
  code=0
  for cmd in "$@"; do
    if ! command -v -- "${cmd}" 1>/dev/null; then
      PrintStderr "\"${cmd}\" not found in \$PATH"
      code=$((code+1))
    fi
  done
  [ "${code}" -eq 0 ] || exit 1
}

CONOHA_CREDENTIALS_FILE="$HOME/.conoha/credentials"

ConoHaConfigure() {
  if [ -e "${CONOHA_CREDENTIALS_FILE}" ]; then
    PrintStderr "already exist: ${CONOHA_CREDENTIALS_FILE}"
    exit 1
  fi
  mkdir -p "$(dirname "${CONOHA_CREDENTIALS_FILE}")"
  echo "ref. https://manage.conoha.jp/API/"
  printf '%s' 'ConoHa Tenant ID: '
  read -r CONOHA_TENANT_ID
  if [ -z "${CONOHA_TENANT_ID}" ]; then
    PrintStderr "Credentials parameters are not set"
    exit 1
  fi
  printf '%s' 'ConoHa API Account Username: '
  read -r CONOHA_API_ACCOUNT_USERNAME
  stty -echo
  printf '%s' 'ConoHa API Account Password: '
  if [ -z "${CONOHA_API_ACCOUNT_USERNAME}" ]; then
    PrintStderr "Credentials parameters are not set"
    exit 1
  fi
  read -r CONOHA_API_ACCOUNT_PASSWORD
  stty echo
  echo
  if [ -z "${CONOHA_API_ACCOUNT_PASSWORD}" ]; then
    PrintStderr "Credentials parameters are not set"
    exit 1
  fi
  {
    echo "CONOHA_TENANT_ID=${CONOHA_TENANT_ID}"
    echo "CONOHA_API_ACCOUNT_USERNAME=${CONOHA_API_ACCOUNT_USERNAME}"
    echo "CONOHA_API_ACCOUNT_PASSWORD=${CONOHA_API_ACCOUNT_PASSWORD}"
  } >"${CONOHA_CREDENTIALS_FILE}"
  chown -R "$(id -u)":"$(id -g)" "$(dirname "${CONOHA_CREDENTIALS_FILE}")"
  chmod -R go-rwx "$(dirname "${CONOHA_CREDENTIALS_FILE}")"
}

ConoHaSetCredentials() {
  CheckDependency curl jq
  if [ -f "${CONOHA_CREDENTIALS_FILE}" ] && [ -r "${CONOHA_CREDENTIALS_FILE}" ]; then
    . "${CONOHA_CREDENTIALS_FILE}"
  else
    PrintStderr "Credentials file does not found: ${CONOHA_CREDENTIALS_FILE}"
    PrintStderr "For set credentials, run:"
    PrintStderr "  $ conoha configure"
    exit 1
  fi
  conoha_api_endpoint="https://identity.tyo1.conoha.io/v2.0/tokens"
  CONOHA_TOKEN=$(
    curl -fsS -X POST "${conoha_api_endpoint}" \
      -H 'Accept: application/json' \
      -d '{"auth":{"passwordCredentials":{"username":"'"${CONOHA_API_ACCOUNT_USERNAME}"'","password":"'"${CONOHA_API_ACCOUNT_PASSWORD}"'"},"tenantId":"'"${CONOHA_TENANT_ID}"'"}}' \
      | jq -r '.access.token.id'
  )
  if [ -z "${CONOHA_TOKEN}" ] || [ "${CONOHA_TOKEN}" = null ]; then
    PrintStderr "CONOHA_TOKEN is null"
    PrintStderr "Please check credentials file: ${CONOHA_CREDENTIALS_FILE}"
    exit 1
  fi
}

ConoHaBase64Encode() {
  CheckDependency base64 openssl
  if command -v base64 1>/dev/null; then
    base64 </dev/stdin
  elif command -v openssl 1>/dev/null; then
    openssl base64 </dev/stdin
  else
    echo "You need \"base64\" or \"openssl\""
    exit 1
  fi
}

ConoHaJSON() {
  if command -v jq 1>/dev/null; then
    "$(command -v jq)" . </dev/stdin
  elif command -v python 1>/dev/null; then
    "$(command -v python)" -m json.tool </dev/stdin
  elif command -v ruby 1>/dev/null; then
    "$(command -v ruby)" -r json -e 'puts JSON.pretty_generate(JSON.parse(STDIN.read))' </dev/stdin
  elif command -v perl 1>/dev/null; then
    # shellcheck disable=SC2016
    "$(command -v perl)" -MEncode -MJSON::PP -e '$json=JSON::PP->new->pretty; $obj=$json->decode(decode_utf8(join("",(<STDIN>)))); print encode_utf8($json->encode($obj))'
  else
    # plain output
    cat /dev/stdin
  fi
}



##
# flavors
##
ConoHaFlavorsList() {
  # ref. https://www.conoha.jp/docs/compute-get_flavors_list.html
  ConoHaSetCredentials
  conoha_api_response=$(
    conoha_api_endpoint="https://compute.tyo1.conoha.io/v2/${CONOHA_TENANT_ID}/flavors"
    curl -fsS -X GET "${conoha_api_endpoint}" \
      -H 'Accept: application/json' \
      -H "X-Auth-Token: ${CONOHA_TOKEN}" \
  )
  echo "${conoha_api_response}" | jq .
}

ConoHaFlavorsListSumally() {
  conoha_api_response=$(ConoHaFlavorsList "$@")
  echo "${conoha_api_response}" | jq '{ flavors: [(.flavors[]|{id,name})] }'
  #echo "${conoha_api_response}" | jq '.flavors[] | { "Key": .name, "Value": .id }' | jq -s 'sort_by( .Key ) | from_entries | { flavors: . }'
}



##
# images
##
ConoHaImagesList() {
  # ref. https://www.conoha.jp/docs/compute-get_images_list.html
  ConoHaSetCredentials
  conoha_api_response=$(
    conoha_api_endpoint="https://compute.tyo1.conoha.io/v2/${CONOHA_TENANT_ID}/images"
    curl -fsS -X GET "${conoha_api_endpoint}" \
      -H "Accept: application/json" \
      -H "X-Auth-Token: ${CONOHA_TOKEN}" \
  )
  echo "${conoha_api_response}" | jq .
}

ConoHaImagesListSumally() {
  conoha_api_response=$(ConoHaImagesList "$@")
  echo "${conoha_api_response}" | jq '{ images: [(.images[]|{id,name})] }'
  #echo "${conoha_api_response}" | jq '.images[] | { "Key": .name, "Value": .id }' | jq -s 'sort_by( .Key ) | from_entries | { images: . }'
}



##
# keypairs
##
ConoHaKeypairsList() {
  # ref. https://www.conoha.jp/docs/compute-get_keypairs.html
  ConoHaSetCredentials
  conoha_api_response=$(
    conoha_api_endpoint="https://compute.tyo1.conoha.io/v2/${CONOHA_TENANT_ID}/os-keypairs"
    curl -fsS -X GET "${conoha_api_endpoint}" \
      -H 'Accept: application/json' \
      -H "X-Auth-Token: ${CONOHA_TOKEN}" \
  )
  echo "${conoha_api_response}" | jq .
}

ConoHaKeypairsUpload() {
  # ref. https://www.conoha.jp/docs/compute-get_keypairs.html
  conoha_key_name="${1:?"$(printf '\n%s' "Set \$1 as Keypair Name")"}"
  conoha_public_key="${2:?"$(printf '\n%s\n%s\n%s' "Set \$2 as Public Key (e.g. \"ssh-rsa AAAAB3NzaC1yc2EAAAA... foobar@localhost\" or \"\$(cat ~/.ssh/id_rsa.pub)\")" "See:" "  $ conoha subnets list")"}"
  ConoHaSetCredentials
  conoha_api_response=$(
    conoha_api_endpoint="https://compute.tyo1.conoha.io/v2/${CONOHA_TENANT_ID}/os-keypairs"
    curl -fsS -X POST "${conoha_api_endpoint}" \
      -H 'Accept: application/json' \
      -H "X-Auth-Token: ${CONOHA_TOKEN}" \
      -d '{"keypair": {"name": "'"${conoha_key_name}"'","public_key": "'"${conoha_public_key}"'"}}' \
  )
  echo "${conoha_api_response}" | jq .
}



##
# networks
##
ConoHaNetworksCreateLocalNetwork() {
  # ref. https://www.conoha.jp/docs/neutron-add_network.html
  ConoHaSetCredentials
  conoha_api_response=$(
    conoha_api_endpoint="https://networking.tyo1.conoha.io/v2.0/networks"
    curl -fsS -X POST "${conoha_api_endpoint}" \
      -H 'Accept: application/json' \
      -H "X-Auth-Token: ${CONOHA_TOKEN}" \
  )
  echo "${conoha_api_response}" | jq .
}

ConoHaNetworksDelete() {
  # ref. https://www.conoha.jp/docs/neutron-remove_network.html
  conoha_network_id="${1:?"$(printf '\n%s\n%s\n%s' "Set \$1 as Network ID (e.g. \"ffffffff-ffff-ffff-ffff-ffffffffffff\")" "See:" "  $ conoha networks list")"}"
  ConoHaSetCredentials
  conoha_api_response=$(
    conoha_api_endpoint="https://networking.tyo1.conoha.io/v2.0/networks/${conoha_network_id}"
    curl -fsS -X DELETE "${conoha_api_endpoint}" \
      -H 'Accept: application/json' \
      -H "X-Auth-Token: ${CONOHA_TOKEN}" \
  )
  echo "${conoha_api_response}" | jq .
}

ConoHaNetworksListLocalNetworks() {
  # ref. https://www.conoha.jp/docs/neutron-get_networks_list.html
  ConoHaSetCredentials
  conoha_api_response=$(
    conoha_api_endpoint="https://networking.tyo1.conoha.io/v2.0/networks"
    curl -fsS -X GET "${conoha_api_endpoint}" \
      -H 'Accept: application/json' \
      -H "X-Auth-Token: ${CONOHA_TOKEN}" \
  )
      echo "${conoha_api_response}" | jq -r '{ networks: [(.networks[]|select(.name|startswith("local-")))] }'
}



##
# ports
##
ConoHaPortsList() {
  # ref. https://www.conoha.jp/docs/neutron-get_ports_list.html
  ConoHaSetCredentials
  conoha_api_response=$(
    conoha_api_endpoint="https://networking.tyo1.conoha.io/v2.0/ports"
    curl -fsS -X GET "${conoha_api_endpoint}" \
      -H 'Accept: application/json' \
      -H "X-Auth-Token: ${CONOHA_TOKEN}" \
  )
  echo "${conoha_api_response}" | jq .
}

ConoHaPortsListSumally() {
  conoha_api_response=$(ConoHaPortsList "$@")
  echo "${conoha_api_response}" | jq '{ ports: [(.ports[]|{id,network_id,fixed_ips})] }'
}

ConoHaPortsCreate() {
  conoha_network_id="${1:?"$(printf '\n%s\n%s\n%s' "Set \$1 as Network ID (e.g. \"ffffffff-ffff-ffff-ffff-ffffffffffff\")" "See:" "  $ conoha subnets list")"}"
  conoha_subnet_id="${2:?"$(printf '\n%s\n%s\n%s' "Set \$2 as Subnet ID (e.g. \"ffffffff-ffff-ffff-ffff-ffffffffffff\")" "See:" "  $ conoha subnets list")"}"
  conoha_ipaddress="${3:?"$(printf '\n%s\n%s\n%s' "Set \$3 as IPAddress (e.g. \"8.8.8.8\")" "See:" "  $ conoha subnets list")"}"
  ConoHaSetCredentials
  conoha_api_response=$(
    conoha_default_security_groups="$(ConoHaSecurityGroupsList | jq '.security_groups[] | select( (.name == "gncs-ipv4-all") or (.name == "default") ) | .id' | jq -cs .)"
    conoha_api_endpoint="https://networking.tyo1.conoha.io/v2.0/ports"
    curl -fsS -X POST "${conoha_api_endpoint}" \
      -H 'Accept: application/json' \
      -H "X-Auth-Token: ${CONOHA_TOKEN}" \
      -d'{"port":{"network_id":"'"${conoha_network_id}"'","fixed_ips":[{"ip_address":"'"${conoha_ipaddress}"'","subnet_id":"'"${conoha_subnet_id}"'"}],"security_groups":'"${conoha_default_security_groups}"'}}' \
  )
  echo "${conoha_api_response}" | jq .
}

ConoHaPortsDelete() {
  conoha_port_id="${1:?"$(printf '\n%s\n%s\n%s' "Set \$1 as Port ID (e.g. \"ffffffff-ffff-ffff-ffff-ffffffffffff\")" "See:" "  $ conoha ports list")"}"
  ConoHaSetCredentials
  conoha_api_response=$(
    conoha_api_endpoint="https://networking.tyo1.conoha.io/v2.0/${conoha_port_id}"
    curl -fsS -X DELETE "${conoha_api_endpoint}" \
      -H 'Accept: application/json' \
      -H "X-Auth-Token: ${CONOHA_TOKEN}" \
  )
  echo "${conoha_api_response}" | jq .
}



##
# securitygroups
##
ConoHaSecurityGroupsList() {
  # ref. https://www.conoha.jp/docs/neutron-get_rules_on_secgroup.html
  ConoHaSetCredentials
  conoha_api_response=$(
    conoha_api_endpoint="https://networking.tyo1.conoha.io/v2.0/security-groups"
    curl -fsS -X GET "${conoha_api_endpoint}" \
      -H 'Accept: application/json' \
      -H "X-Auth-Token: ${CONOHA_TOKEN}" \
  )
  echo "${conoha_api_response}" | jq .
}

ConoHaSecurityGroupsListSumally() {
  conoha_api_response=$(ConoHaSecurityGroupsList "$@")
  echo "${conoha_api_response}" | jq '{ security_groups: [(.security_groups[]|{tenant_id,description,id,name})] }'
}



##
# servers
##
ConoHaServersAttachPort() {
  conoha_server_id="${1:?"$(printf '\n%s\n%s\n%s' "Set \$1 as Server ID (e.g. \"ffffffff-ffff-ffff-ffff-ffffffffffff\")" "See:" "  $ conoha servers list")"}"
  conoha_port_id="${2:?"$(printf '\n%s\n%s\n%s' "Set \$2 as Port ID (e.g. \"ffffffff-ffff-ffff-ffff-ffffffffffff\")" "See:" "  $ conoha ports list")"}"
  ConoHaSetCredentials
  conoha_api_endpoint="https://compute.tyo1.conoha.io/v2/${CONOHA_TENANT_ID}/servers/${conoha_server_id}/os-interface"
  conoha_api_response=$(
    curl -fsS -X POST "${conoha_api_endpoint}" \
      -H 'Accept: application/json' \
      -H "X-Auth-Token: ${CONOHA_TOKEN}" \
      -d '{"interfaceAttachment":{"port_id":"'"${conoha_port_id}"'"}}' \
  )
  echo "${conoha_api_response}" | jq .
}

ConoHaServersCreate() {
  # ref. https://www.conoha.jp/docs/compute-create_vm.html
  conoha_flavor_id="${1:?"$(printf '\n%s\n%s\n%s' "Set \$1 as VM Flavor ID (e.g. \"d92b02ce-9a4f-4544-8d7f-ae8380bc08e7\")" "See:" "  $ conoha flavors list")"}"
  conoha_image_id="${2:?"$(printf '\n%s\n%s\n%s' "Set \$2 as VM Image ID (e.g. \"1ae808e4-f4ee-4ee6-adfc-0ba8c2bf67f3\")" "See:" "  $ conoha images list")"}"
  conoha_root_password="${3:?"$(printf '\n%s' "Set \$3 as VM OS Password (e.g. \"C0n0H@P@ssw0rd\")")"}"
  conoha_key_name="${4:?"$(printf '\n%s\n%s\n%s' "Set \$4 as VM OS Keypair Name (e.g. \"foobar\")" "See:" "  $ conoha keypairs list")"}"
  conoha_userdata_base64_encoded="${5:?"$(printf '\n%s\n%s\n%s' "Set \$5 as base64-encoded user-data (e.g. \"IyEvYmluL3NoCmRhdGUK\")" "If you want to encode base64, run:" "  $ cat \"\${YOUR_USER_DATA_FILE:?}\" | openssl base64")"}"
  conoha_name_tag="${6:?"$(printf '\n%s' "Set \$6 as VM Name Tag (e.g. \"bastion\")")"}"
  # CONOHA_SERVERS_CREATE_METADATA は環境変数経由で渡す用
  ConoHaSetCredentials
  conoha_api_response=$(
    conoha_api_endpoint="https://compute.tyo1.conoha.io/v2/${CONOHA_TENANT_ID}/servers"
    curl -fsS -X POST "${conoha_api_endpoint}" \
      -H 'Accept: application/json' \
      -H "X-Auth-Token: ${CONOHA_TOKEN}" \
      -d '{"server":{"flavorRef":"'"${conoha_flavor_id}"'","imageRef":"'"${conoha_image_id}"'","adminPass":"'"${conoha_root_password}"'","key_name":"'"${conoha_key_name}"'","security_groups":[{"name":"default"},{"name":"gncs-ipv4-all"}],"user_data":"'"${conoha_userdata_base64_encoded}"'","metadata":{"instance_name_tag":"'"${conoha_name_tag}"'"'"${CONOHA_SERVERS_CREATE_METADATA}"'}}}' \
  )
  echo "${conoha_api_response}" | jq .
}

ConoHaServersDelete() {
  # ref. https://www.conoha.jp/docs/compute-delete_vm.html
  conoha_server_id="${1:?"$(printf '\n%s\n%s\n%s' "Set \$1 as Server ID (e.g. \"ffffffff-ffff-ffff-ffff-ffffffffffff\")" "See:" "  $ conoha servers list")"}"
  ConoHaSetCredentials
  conoha_api_response=$(
    conoha_api_endpoint="https://compute.tyo1.conoha.io/v2/${CONOHA_TENANT_ID}/servers/${conoha_server_id}"
    curl -fsS -X DELETE "${conoha_api_endpoint}" \
      -H 'Accept: application/json' \
      -H "X-Auth-Token: ${CONOHA_TOKEN}" \
  )
  echo "${conoha_api_response}" | jq .
}

ConoHaServersDeleteWithConfirm() {
  # ref. https://www.conoha.jp/docs/compute-delete_vm.html
  conoha_server_id="${1:?"$(printf '\n%s\n%s\n%s' "Set \$1 as Server ID (e.g. \"ffffffff-ffff-ffff-ffff-ffffffffffff\")" "See:" "  $ conoha servers list")"}"
  ConoHaSetCredentials
  conoha_servers_deleting=$(ConoHaServersListDetail | jq -r '{ servers: [(.servers[]|select(.id =="'"${conoha_server_id}"'"))] }')
  PrintStderr "Terminate servers:"
  echo "${conoha_servers_deleting}" | jq -r '.servers[]|.metadata.instance_name_tag+" ("+.id+", "+(.addresses[]|.[]|select(.version==4)|.addr)+")"' | while read -r LINE; do
    PrintStderr "  - ${LINE}"
  done
  PrintStderr "If you want to cancel, please press Ctrl+C within 10 seconds ..."
  sleep 10
  ConoHaServersDelete "${conoha_server_id}"
  echo "${conoha_api_response}" | jq .
}

ConoHaServersList() {
  # ref. https://www.conoha.jp/docs/compute-get_vms_list.html
  ConoHaSetCredentials
  conoha_api_response=$(
    conoha_api_endpoint="https://compute.tyo1.conoha.io/v2/${CONOHA_TENANT_ID}/servers"
    curl -fsS -X GET "${conoha_api_endpoint}" \
      -H 'Accept: application/json' \
      -H "X-Auth-Token: ${CONOHA_TOKEN}" \
  )
  echo "${conoha_api_response}" | jq .
}

ConoHaServersListDetail() {
  # ref. https://www.conoha.jp/docs/compute-get_vms_detail.html
  ConoHaSetCredentials
  conoha_api_response=$(
    conoha_api_endpoint="https://compute.tyo1.conoha.io/v2/${CONOHA_TENANT_ID}/servers/detail"
    curl -fsS -X GET "${conoha_api_endpoint}" \
      -H 'Accept: application/json' \
      -H "X-Auth-Token: ${CONOHA_TOKEN}" \
  )
  echo "${conoha_api_response}" | jq .
}

ConoHaServersListDetailSumally() {
  conoha_api_response=$(ConoHaServersListDetail "$@")
  echo "${conoha_api_response}" | jq '{ servers: [(.servers[]|{name_tag:.metadata.instance_name_tag,id,name,status,addresses:[(.addresses[]|.[]|.addr)]})] }'
}

ConoHaServersListAttachedPorts() {
  # ref. https://www.conoha.jp/docs/compute-get_attached_ports_list.html
  conoha_server_id="${1:?"$(printf '\n%s\n%s\n%s' "Set \$1 as Server ID (e.g. \"ffffffff-ffff-ffff-ffff-ffffffffffff\")" "See:" "  $ conoha servers list")"}"
  ConoHaSetCredentials
  conoha_api_response=$(
    conoha_api_endpoint="https://compute.tyo1.conoha.io/v2/${CONOHA_TENANT_ID}/servers/${conoha_server_id}/os-interface"
    curl -fsS -X GET "${conoha_api_endpoint}" \
      -H 'Accept: application/json' \
      -H "X-Auth-Token: ${CONOHA_TOKEN}" \
  )
  echo "${conoha_api_response}" | jq .
}

ConoHaServersStart() {
  conoha_server_id="${1:?"$(printf '\n%s\n%s\n%s' "Set \$1 as Server ID (e.g. \"ffffffff-ffff-ffff-ffff-ffffffffffff\")" "See:" "  $ conoha servers list")"}"
  ConoHaSetCredentials
  conoha_api_response=$(
    conoha_api_endpoint="https://compute.tyo1.conoha.io/v2/${CONOHA_TENANT_ID}/servers/${conoha_server_id}/action"
    curl -fsS -X POST "${conoha_api_endpoint}" \
      -H 'Accept: application/json' \
      -H "X-Auth-Token: ${CONOHA_TOKEN}" \
      -d '{"os-start":null}' \
  )
  echo "${conoha_api_response}" | jq .
}

ConoHaServersStop() {
  conoha_server_id="${1:?"$(printf '\n%s\n%s\n%s' "Set \$1 as Server ID (e.g. \"ffffffff-ffff-ffff-ffff-ffffffffffff\")" "See:" "  $ conoha servers list")"}"
  ConoHaSetCredentials
  conoha_api_response=$(
    conoha_api_endpoint="https://compute.tyo1.conoha.io/v2/${CONOHA_TENANT_ID}/servers/${conoha_server_id}/action"
    curl -fsS -X POST "${conoha_api_endpoint}" \
      -H 'Accept: application/json' \
      -H "X-Auth-Token: ${CONOHA_TOKEN}" \
      -d '{"os-stop":null}' \
  )
  echo "${conoha_api_response}" | jq .
}



##
# subnets
##
ConoHaSubnetsCreateLocalSubnet() {
  # ref. https://www.conoha.jp/docs/neutron-add_network.html
  conoha_subnet_network_id="${1:?"$(printf '\n%s\n%s\n%s' "Set \$1 as Network ID (e.g. \"ffffffff-ffff-ffff-ffff-ffffffffffff\")" "See:" "  $ conoha networks list")"}"
  conoha_subnet_cidr="${2:?"$(printf '\n%s' "Set \$2 as Subnet CIDR (e.g. \"10.5.8.0/24\") bitmask require 21-27")"}"
  ConoHaSetCredentials
  conoha_api_response=$(
    conoha_api_endpoint="https://networking.tyo1.conoha.io/v2.0/subnets"
    curl -fsS -X POST "${conoha_api_endpoint}" \
      -H 'Accept: application/json' \
      -H "X-Auth-Token: ${CONOHA_TOKEN}" \
      -d '{"subnet": {"network_id": "'"${conoha_subnet_network_id}"'", "cidr": "'"${conoha_subnet_cidr}"'"}}' \
  )
  echo "${conoha_api_response}" | jq .
}

ConoHaSubnetsDelete() {
  # ref. https://www.conoha.jp/docs/neutron-remove_subnet.html
  conoha_subnet_id="${1:?"$(printf '\n%s\n%s\n%s' "Set \$1 as Subnet ID (e.g. \"ffffffff-ffff-ffff-ffff-ffffffffffff\")" "See:" "  $ conoha subnets list")"}"
  ConoHaSetCredentials
  conoha_api_response=$(
    conoha_api_endpoint="https://networking.tyo1.conoha.io/v2.0/subnets/${conoha_subnet_id}"
    curl -fsS -X DELETE "${conoha_api_endpoint}" \
      -H 'Accept: application/json' \
      -H "X-Auth-Token: ${CONOHA_TOKEN}" \
  )
  echo "${conoha_api_response}" | jq .
}

ConoHaSubnetsList() {
  # ref. https://www.conoha.jp/docs/neutron-get_subnets_list.html
  ConoHaSetCredentials
  conoha_api_response=$(
    conoha_api_endpoint="https://networking.tyo1.conoha.io/v2.0/subnets"
    curl -fsS -X GET "${conoha_api_endpoint}" \
      -H 'Accept: application/json' \
      -H "X-Auth-Token: ${CONOHA_TOKEN}" \
  )
  echo "${conoha_api_response}" | jq -r .
}

ConoHaSubnetsListLocalSubnets() {
  conoha_api_response=$(ConoHaSubnetsList "$@")
  echo "${conoha_api_response}" | jq -r '{ subnets: [(.subnets[]|select(.name|startswith("local-")))] }'
}

ConoHaSubnetsListAdditionalIPAddresses() {
  conoha_api_response=$(ConoHaSubnetsList "$@")
  echo "${conoha_api_response}" | jq '{ subnets: [(.subnets[]|select(.cidr|match("/32")))] }'
}



##
# tools
##
ConoHaToolsGetImageUbuntu1804() {
  conoha_api_response=$(ConoHaImagesList "$@")
  echo "${conoha_api_response}" | jq '.images | sort_by(.name) | .[] | select(.name | match("vmi-ubuntu-18.04-amd64-20gb"))'
}

ConoHaToolsGetFlavor512MB() {
  conoha_api_response=$(ConoHaFlavorsList "$@")
  echo "${conoha_api_response}" | jq '.flavors[] | select(.name == "g-512mb")'
}

ConoHaToolsGetFlavor1GB() {
  conoha_api_response=$(ConoHaFlavorsList "$@")
  echo "${conoha_api_response}" | jq '.flavors[] | select(.name == "g-1gb")'
}

ConoHaKubernetesCreateClusterSingleMaster() {
  CheckDependency ssh
  #set -x  ## for DEBUG
  conoha_k8s_cluster_name="${1:?"$(printf '\n%s' "Set \$1 as Kubernetes cluster name")"}"
  conoha_log=~/.conoha.log ; touch "${conoha_log}" ; chmod go-rwx "${conoha_log}"
  conoha_k8s_kube_config_dir=~/.conoha/.kube ; mkdir -p "${conoha_k8s_kube_config_dir}"
  conoha_k8s_kube_config_file="${conoha_k8s_kube_config_dir}/config" ; touch "${conoha_k8s_kube_config_file}"
  conoha_k8s_known_hosts=~/.conoha/known_hosts ; touch "${conoha_k8s_known_hosts}"
  chmod -R go-rwx "${conoha_k8s_kube_config_dir}"
  # TODO: k8sクラスタをInternalで構築したかった
  #local#conoha_subnet_name="local-10-5-8-0-24"
  #local#conoha_subnet_cidr="10.5.8.0/24"
  #local#conoha_master001_ipaddress="10.5.8.101"
  conoha_key_file="${HOME}/.ssh/id_rsa"
  conoha_flavor_id="7eea7469-0d85-4f82-8050-6ae742394681"  ## g-1gb 810JPY/month
  conoha_image_id="1ae808e4-f4ee-4ee6-adfc-0ba8c2bf67f3"  ## vmi-ubuntu-18.04-amd64-20gb
  conoha_root_password=$(LANG=C LC_ALL=C tr -dc 0-9A-Za-z </dev/urandom | head -c 16 || true)
  conoha_key_name="${conoha_k8s_cluster_name}"
  conoha_k8s_master001_name_tag="${conoha_k8s_cluster_name}master001"
  conoha_k8s_worker001_name_tag="${conoha_k8s_cluster_name}worker001"
  conoha_k8s_worker002_name_tag="${conoha_k8s_cluster_name}worker002"
  PrintStderr "Checking user-data script https://djeeno.gitlab.io/user-data/kubernetes-master.sh ..."
  conoha_userdata_master=$(curl -LRsS https://djeeno.gitlab.io/user-data/kubernetes-master.sh)
  PrintStderr "Checking user-data script https://djeeno.gitlab.io/user-data/kubernetes-worker.sh ..."
  conoha_userdata_worker=$(curl -LRsS https://djeeno.gitlab.io/user-data/kubernetes-worker.sh)
  conoha_userdata_base64_encoded_k8s_master001=$(echo "${conoha_userdata_master}" | sed "s/localhost/${conoha_k8s_master001_name_tag}/" | ConoHaBase64Encode)
  conoha_userdata_base64_encoded_k8s_worker001=$(echo "${conoha_userdata_worker}" | sed "s/localhost/${conoha_k8s_worker001_name_tag}/" | ConoHaBase64Encode)
  conoha_userdata_base64_encoded_k8s_worker002=$(echo "${conoha_userdata_worker}" | sed "s/localhost/${conoha_k8s_worker002_name_tag}/" | ConoHaBase64Encode)
  #local###
  #local## サブネット作成
  #local###
  #local#if [ "$(ConoHaSubnetsList | jq -r '.subnets[] | select( .name == "'"${conoha_subnet_name}"'" ) | any(.)')" ]; then 
  #local#  # local- で始まるネットワークが存在しない場合作成する
  #local#  conoha_api_response=$(ConoHaNetworksCreateLocalNetwork)
  #local#  conoha_network_id=$(echo "${conoha_api_response}" | jq -r .network.id)
  #local#  if [ -z "${conoha_network_id}" ]; then
  #local#    PrintStderr "failed to \"conoha networks create-local-network\""
  #local#    exit 1
  #local#  fi
  #local#  # subnet 作成
  #local#  ConoHaSubnetsCreateLocalSubnet "${conoha_network_id}" "${conoha_subnet_cidr}"
  #local#fi
  #local###
  #local## ポート作成
  #local###
  #local#if [ "$(ConoHaPortsList | jq -r '.ports[] | select( .name | startswith("local-") ) | .fixed_ips[] | select( .ip_address == "'"${conoha_master001_ipaddress}"'" ) | any(.)')" != true ]; then
  #local#  conoha_api_response=$(ConoHaSubnetsList)
  #local#  conoha_network_id=$(echo "${conoha_api_response}" | jq -r '.subnets[] | select( .name == "'"${conoha_subnet_name}"'" ) | .network_id')
  #local#  conoha_subnet_id=$(echo "${conoha_api_response}" | jq -r '.subnets[] | select( .name == "'"${conoha_subnet_name}"'" ) | .id')
  #local#  ConoHaPortsCreate "${conoha_network_id}" "${conoha_subnet_id}" "${conoha_master001_ipaddress}"
  #fi
  PrintStderr "Setup Kubernetes cluster \"${conoha_k8s_cluster_name}\""
  ##
  # キーペア作成
  ##
  PrintStderr "Checking existence of keypair \"${conoha_key_name}\" ..."
  conoha_keypairs_list_response=$(ConoHaKeypairsList)
  if [ "$(echo "${conoha_keypairs_list_response}" | jq '.keypairs[] | select( .keypair.name == "'"${conoha_key_name}"'" ) | any(.)')" != true ]; then
    if ! grep -q ssh- "${conoha_key_file}.pub" 2>/dev/null; then
      PrintStderr "You need ${conoha_key_file}.pub"
      PrintStderr "  $ echo | ssh-keygen -t rsa -N '' -f \"${conoha_key_file}\""
      exit 1
    fi
    PrintStderr "Create keypair \"${conoha_key_name}\""
    ConoHaKeypairsUpload "${conoha_key_name}" "$(cat ~/.ssh/id_rsa.pub)" 1>>"${conoha_log}"
  else
    # すでに存在する鍵を利用
    PrintStderr "Keypair \"${conoha_key_name}\" already exists so using it."
  fi
  ##
  # Kubernetes master001 node サーバ作成
  ##
  PrintStderr "Checking existence of server \"${conoha_k8s_master001_name_tag}\" ..."
  conoha_servers_list_detail_response=$(ConoHaServersListDetail)
  if [ "$(echo "${conoha_servers_list_detail_response}" | jq -r '.servers[] | select( .metadata.instance_name_tag == "'"${conoha_k8s_master001_name_tag}"'" ) | any(.)')" != true ]; then
    PrintStderr "Create server \"${conoha_k8s_master001_name_tag}\""
    conoha_server_create_response=$(
      # shellcheck disable=SC2030,SC2031
      export CONOHA_SERVERS_CREATE_METADATA=',"kubernetes_cluster_name":"'"${conoha_k8s_cluster_name}"'","kubernetes_cluster_role":"master","kubernetes_cluster_type":"single_master"'
      ConoHaServersCreate "${conoha_flavor_id}" "${conoha_image_id}" "${conoha_root_password}" "${conoha_key_name}" "${conoha_userdata_base64_encoded_k8s_master001}" "${conoha_k8s_master001_name_tag}"
    )
    echo "${conoha_server_create_response}" | jq -cr . 1>>"${conoha_log}"
  else
    conoha_k8s_master001_status=$(echo "${conoha_servers_list_detail_response}" | jq -r '.servers[] | select( .metadata.instance_name_tag == "'"${conoha_k8s_master001_name_tag}"'" ) | .status')
    if [ "${conoha_k8s_master001_status}" != "ACTIVE" ] && [ "${conoha_k8s_master001_status}" != "BUILD" ]; then
      PrintStderr "Server \"${conoha_k8s_master001_name_tag}\" already exists, but status is \"${conoha_k8s_master001_status}\""
      PrintStderr "See:"
      PrintStderr "  $ conoha servers list-detail | jq '.servers[] | select( .metadata.instance_name_tag == \"${conoha_k8s_master001_name_tag}\" )'"
      exit 0
    fi
  fi
  ##
  # Kubernetes worker001 node サーバ作成
  ##
  PrintStderr "Checking existence of server \"${conoha_k8s_worker001_name_tag}\" ..."
  conoha_servers_list_detail_response=$(ConoHaServersListDetail)
  if [ "$(echo "${conoha_servers_list_detail_response}" | jq -r '.servers[] | select( .metadata.instance_name_tag == "'"${conoha_k8s_worker001_name_tag}"'" ) | any(.)')" != true ]; then
    PrintStderr "Create server \"${conoha_k8s_worker001_name_tag}\""
    conoha_server_create_response=$(
      # shellcheck disable=SC2030,SC2031
      export CONOHA_SERVERS_CREATE_METADATA=',"kubernetes_cluster_name":"'"${conoha_k8s_cluster_name}"'","kubernetes_cluster_role":"worker","kubernetes_cluster_type":"single_master"'
      ConoHaServersCreate "${conoha_flavor_id}" "${conoha_image_id}" "${conoha_root_password}" "${conoha_key_name}" "${conoha_userdata_base64_encoded_k8s_worker001}" "${conoha_k8s_worker001_name_tag}"
    )
    echo "${conoha_server_create_response}" | jq -cr . 1>>"${conoha_log}"
  else
    conoha_k8s_worker001_status=$(echo "${conoha_servers_list_detail_response}" | jq -r '.servers[] | select( .metadata.instance_name_tag == "'"${conoha_k8s_worker001_name_tag}"'" ) | .status')
    if [ "${conoha_k8s_worker001_status}" != "ACTIVE" ] && [ "${conoha_k8s_worker001_status}" != "BUILD" ]; then
      PrintStderr "Server \"${conoha_k8s_worker001_name_tag}\" already exists, but status is \"${conoha_k8s_worker001_status}\""
      PrintStderr "See:"
      PrintStderr "  $ conoha servers list-detail | jq '.servers[] | select( .metadata.instance_name_tag == \"${conoha_k8s_worker001_name_tag}\" )'"
      exit 0
    fi
  fi
  ##
  # Kubernetes worker002 node サーバ作成
  ##
  PrintStderr "Checking existence of server \"${conoha_k8s_worker002_name_tag}\" ..."
  conoha_servers_list_detail_response=$(ConoHaServersListDetail)
  if [ "$(echo "${conoha_servers_list_detail_response}" | jq -r '.servers[] | select( .metadata.instance_name_tag == "'"${conoha_k8s_worker002_name_tag}"'" ) | any(.)')" != true ]; then
    PrintStderr "Create server \"${conoha_k8s_worker002_name_tag}\""
    conoha_server_create_response=$(
      # shellcheck disable=SC2030,SC2031
      export CONOHA_SERVERS_CREATE_METADATA=',"kubernetes_cluster_name":"'"${conoha_k8s_cluster_name}"'","kubernetes_cluster_role":"worker","kubernetes_cluster_type":"single_master"'
      ConoHaServersCreate "${conoha_flavor_id}" "${conoha_image_id}" "${conoha_root_password}" "${conoha_key_name}" "${conoha_userdata_base64_encoded_k8s_worker002}" "${conoha_k8s_worker002_name_tag}"
    )
    echo "${conoha_server_create_response}" | jq -cr . 1>>"${conoha_log}"
  else
    conoha_k8s_worker002_status=$(echo "${conoha_servers_list_detail_response}" | jq -r '.servers[] | select( .metadata.instance_name_tag == "'"${conoha_k8s_worker002_name_tag}"'" ) | .status')
    if [ "${conoha_k8s_worker002_status}" != "ACTIVE" ] && [ "${conoha_k8s_worker002_status}" != "BUILD" ]; then
      PrintStderr "Server \"${conoha_k8s_worker002_name_tag}\" already exists, but status is \"${conoha_k8s_worker002_status}\""
      PrintStderr "See:"
      PrintStderr "  $ conoha servers list-detail | jq '.servers[] | select( .metadata.instance_name_tag == \"${conoha_k8s_worker002_name_tag}\" )'"
      exit 0
    fi
  fi
  ####
  #
  # Kubernetes master001
  #
  ####
  ##
  # Kubernetes master001 node に sshできるようになるまで待つ
  ##
  PrintStderr "Checking to connect to server \"${conoha_k8s_master001_name_tag}\" ..."
  conoha_ssh_user="${SSH_USER:-"root"}"
  SSH_OPTIONS="-o PasswordAuthentication=no -o IdentityFile=${conoha_key_file} -o StrictHostKeyChecking=no -o UserKnownHostsFile=${conoha_k8s_known_hosts}"
  # shellcheck disable=SC2086
  sshCmd() { ssh -n ${SSH_OPTIONS} "$@"; }
  conoha_ssh_host_k8s_master001=
  while true; do
    conoha_ssh_host_k8s_master001=$(
      ConoHaServersListDetail | jq -r '.servers[] | select( .metadata.instance_name_tag == "'"${conoha_k8s_master001_name_tag}"'" ) | .addresses | .[] | .[] | select( .version == 4 ) | .addr'
    )
    [ -z "${conoha_ssh_host_k8s_master001}" ] || break
    sleep 10
    PrintStderr "Waiting to ssh to \"${conoha_k8s_master001_name_tag}\" ..."
  done
  ##
  # Kubernetes master001 node の kubeadm init の完了 ＆ kubeadm join コマンドの出力を待つ
  ##
  PrintStderr "Getting kubeadm join command on \"${conoha_k8s_master001_name_tag}\" ..."
  conoha_k8s_worker_join_command=
  while true; do
    conoha_k8s_worker_join_command=$(sshCmd "${conoha_ssh_user}"@"${conoha_ssh_host_k8s_master001}" "grep -o 'kubeadm join .*$' /root/.user-data/output.log 2>/dev/null | tail -n 1 | tee ~/.kube/join" || true)
    [ -z "${conoha_k8s_worker_join_command}" ] || break
    sleep 10
    PrintStderr "Waiting kubeadm init on \"${conoha_k8s_master001_name_tag}\" ..."
  done
  ##
  # Kubernetes master001 node から /etc/kubernetes/admin.conf をダウンロード
  ##
  PrintStderr "Downloading \"/etc/kubernetes/admin.conf\" on \"${conoha_k8s_master001_name_tag}\" as \"${conoha_k8s_kube_config_file}\" ..."
  conoha_k8s_admin_config_content=
  while true; do
    conoha_k8s_admin_config_content=$(sshCmd "${conoha_ssh_user}"@"${conoha_ssh_host_k8s_master001}" "cat /etc/kubernetes/admin.conf" || true)
    [ -z "${conoha_k8s_admin_config_content}" ] || break
    sleep 10
    PrintStderr "Waiting to generate \"/etc/kubernetes/admin.conf\" on \"${conoha_k8s_master001_name_tag}\" ..."
  done
  echo "${conoha_k8s_admin_config_content}" >"${conoha_k8s_kube_config_file}"
  sshCmd "${conoha_ssh_user}"@"${conoha_ssh_host_k8s_master001}" """
    grep -q \"kubeadm completion bash\" ~/.bashrc || echo \"eval \\\"\\\$(kubeadm completion bash)\\\"\" 1>>~/.bashrc
    grep -q \"kubectl completion bash\" ~/.bashrc || echo \"eval \\\"\\\$(kubectl completion bash)\\\"\" 1>>~/.bashrc
  """
  ####
  #
  # Kubernetes worker001
  #
  ####
  ##
  # Kubernetes worker001 node に sshできるようになるまで待つ
  ##
  PrintStderr "Checking to connect to server \"${conoha_k8s_worker001_name_tag}\" ..."
  conoha_ssh_host_k8s_worker001=
  while true; do
    conoha_ssh_host_k8s_worker001=$(
      ConoHaServersListDetail | jq -r '.servers[] | select( .metadata.instance_name_tag == "'"${conoha_k8s_worker001_name_tag}"'" ) | .addresses | .[] | .[] | select( .version == 4 )   | .addr'
    )
    [ -z "${conoha_ssh_host_k8s_worker001}" ] || break
    sleep 10
    PrintStderr "Waiting to ssh to \"${conoha_k8s_worker001_name_tag}\" ..."
  done
  ##
  # Kubernetes worker001 node に ~/.kube/config をアップロード
  ##
  PrintStderr "Uploading \"${conoha_k8s_kube_config_file}\" as \"~/.kube/config\" to worker node \"${conoha_k8s_worker001_name_tag}\" ..."
  sshCmd "${conoha_ssh_user}"@"${conoha_ssh_host_k8s_worker001}" "[ -f ~/.kube/config ] || { mkdir -p ~/.kube; echo '${conoha_k8s_admin_config_content}' >~/.kube/config; }"
  sshCmd "${conoha_ssh_user}"@"${conoha_ssh_host_k8s_worker001}" """
    grep -q \"kubeadm completion bash\" ~/.bashrc || echo \"eval \\\"\\\$(kubeadm completion bash)\\\"\" 1>>~/.bashrc
    grep -q \"kubectl completion bash\" ~/.bashrc || echo \"eval \\\"\\\$(kubectl completion bash)\\\"\" 1>>~/.bashrc
  """
  ##
  # Kubernetes worker001 node で kubeadm join コマンドを実行
  ##
  PrintStderr "Join the cluster if worker node \"${conoha_k8s_worker001_name_tag}\" does not participate in kubernetes cluster"
  sshCmd "${conoha_ssh_user}"@"${conoha_ssh_host_k8s_worker001}" "kubectl get nodes | grep -q \"^\$(hostname --short | cut -b1-16)\" || ${conoha_k8s_worker_join_command}"
  ####
  #
  # Kubernetes worker002
  #
  ####
  ##
  # Kubernetes worker002 node に sshできるようになるまで待つ
  ##
  PrintStderr "Checking to connect to server \"${conoha_k8s_worker002_name_tag}\" ..."
  conoha_ssh_host_k8s_worker002=
  while true; do
    conoha_ssh_host_k8s_worker002=$(
      ConoHaServersListDetail | jq -r '.servers[] | select( .metadata.instance_name_tag == "'"${conoha_k8s_worker002_name_tag}"'" ) | .addresses | .[] | .[] | select( .version == 4 )   | .addr'
    )
    [ -z "${conoha_ssh_host_k8s_worker002}" ] || break
    sleep 10
    PrintStderr "Waiting to ssh to \"${conoha_k8s_worker002_name_tag}\" ..."
  done
  ##
  # Kubernetes worker002 node に ~/.kube/config をアップロード
  ##
  PrintStderr "Uploading \"${conoha_k8s_kube_config_file}\" as \"~/.kube/config\" to worker node \"${conoha_k8s_worker002_name_tag}\" ..."
  sshCmd "${conoha_ssh_user}"@"${conoha_ssh_host_k8s_worker002}" "[ -f ~/.kube/config ] || { mkdir -p ~/.kube; echo '${conoha_k8s_admin_config_content}' >~/.kube/config; }"
  sshCmd "${conoha_ssh_user}"@"${conoha_ssh_host_k8s_worker002}" """
    grep -q \"kubeadm completion bash\" ~/.bashrc || echo \"eval \\\"\\\$(kubeadm completion bash)\\\"\" 1>>~/.bashrc
    grep -q \"kubectl completion bash\" ~/.bashrc || echo \"eval \\\"\\\$(kubectl completion bash)\\\"\" 1>>~/.bashrc
  """
  ##
  # Kubernetes worker002 node で kubeadm join コマンドを実行
  ##
  PrintStderr "Join the cluster if worker node \"${conoha_k8s_worker002_name_tag}\" does not participate in kubernetes cluster"
  sshCmd "${conoha_ssh_user}"@"${conoha_ssh_host_k8s_worker002}" "kubectl get nodes | grep -q \"^\$(hostname --short | cut -b1-16)\" || ${conoha_k8s_worker_join_command}"
  ##
  # for access
  ##
  PrintStderr "If connecting to master node \"${conoha_k8s_master001_name_tag}\", do the following:"
  PrintStderr "  $ ssh ${SSH_OPTIONS} ${conoha_ssh_user}@${conoha_ssh_host_k8s_master001}  ## ${conoha_k8s_master001_name_tag}"
  PrintStderr "If connecting to worker node \"${conoha_k8s_worker001_name_tag}\", do the following:"
  PrintStderr "  $ ssh ${SSH_OPTIONS} ${conoha_ssh_user}@${conoha_ssh_host_k8s_worker001}  ## ${conoha_k8s_worker001_name_tag}"
  PrintStderr "If connecting to worker node \"${conoha_k8s_worker002_name_tag}\", do the following:"
  PrintStderr "  $ ssh ${SSH_OPTIONS} ${conoha_ssh_user}@${conoha_ssh_host_k8s_worker002}  ## ${conoha_k8s_worker002_name_tag}"
  ##
  # kubectl get の結果を出力
  ##
  PrintStderr "$ export KUBECONFIG=${conoha_k8s_kube_config_file}"
  export KUBECONFIG="${conoha_k8s_kube_config_file}"
  PrintStderr "$ kubectl get nodes"
  kubectl get nodes
  PrintStderr "$ kubectl get pods --namespace=kube-system"
  kubectl get pods --namespace=kube-system
}

ConoHaKubernetesListClustersJSON() {
  ConoHaServersListDetail | jq -r '{ clusters: ([.servers[].metadata.kubernetes_cluster_name|select(.!=null)]|unique) }'
}

ConoHaKubernetesListClusters() {
  ConoHaKubernetesListClustersJSON | jq -r '.clusters[] | [(.)] | @tsv'
}

ConoHaKubernetesListClusterNodes() {
  ConoHaKubernetesListClusterNodesJSON "$@" | jq -r '.servers[] | [(.addresses|.[]|.[]|select(.version==4)|.addr), (.metadata|.instance_name_tag, .kubernetes_cluster_role)] | @tsv'
}

ConoHaKubernetesListClusterNodesJSON() {
  conoha_k8s_cluster_name="${1:?"$(printf '\n%s' "Set \$1 as Kubernetes cluster name")"}"
  conoha_servers_list_detail=$(ConoHaServersListDetail | jq -r '{ servers: [(.servers[] | select(.metadata.kubernetes_cluster_name == "'"${conoha_k8s_cluster_name}"'"))]}')
  if [ -n "${conoha_servers_list_detail}" ]; then
    echo "${conoha_servers_list_detail}" | jq -r
  fi
}

ConoHaKubernetesTerminateCluster() {
  conoha_k8s_cluster_name="${1:?"$(printf '\n%s' "Set \$1 as Kubernetes cluster name")"}"
  conoha_servers_k8s_cluster_nodes=$(ConoHaServersListDetail | jq -r '{ servers: [(.servers[]|select(.metadata.kubernetes_cluster_name=="'"${conoha_k8s_cluster_name}"'"))] }')
  conoha_servers_name_tags=$(echo "${conoha_servers_k8s_cluster_nodes}" | jq -r '.servers[] | .metadata.instance_name_tag')
  if [ -n "${conoha_servers_name_tags}" ]; then
    PrintStderr "Terminate servers:"
    echo "${conoha_servers_k8s_cluster_nodes}" | jq -r '.servers[]|.metadata.instance_name_tag+" ("+.id+", "+(.addresses[]|.[]|select(.version==4)|.addr)+")"' | while read -r LINE; do
      PrintStderr "  - ${LINE}"
    done
    PrintStderr "If you want to cancel, please press Ctrl+C within 10 seconds ..."
    sleep 10
    echo "${conoha_servers_k8s_cluster_nodes}" | jq -r '.servers[] | .id' | while read -r LINE; do
      ConoHaServersDelete "${LINE}"
    done
  else
    PrintStderr "Kubernetes cluster \"${conoha_k8s_cluster_name}\" not found"
  fi
}



##
# main
##
ConohaMain() {  ## main start DO NOT REMOVE ##
  sub_command="$1"
  sub2_command="$2"

  if [ "$2" ]; then shift || true; fi
  if [ "$1" ]; then shift || true; fi

  # shellcheck disable=SC2034
  conoha_main_method_content=$(
    conoha_main_tail=$(tail -n +"$(grep -n "## main start DO NOT REMOVE ##$" "$0" | cut -d: -f1)" "$0")
    echo "${conoha_main_tail}" | head -n "$(echo "${conoha_main_tail}" | grep -n "## main end DO NOT REMOVE ##$" | cut -d: -f1)"
  )

  # shellcheck disable=1004,SC2016
  get_sub_cmds='''
    printf "%s" "${conoha_main_method_content}" \
      | grep -Eo "^ {4}[^ ]+ *)" \
      | grep -Ev "^ {4}(subcmds|\*|completion)" \
      | tr -d "\n" \
      | sed "s/ *//g; s/)/ /g; s/ *$//g"
  '''

  # shellcheck disable=1004,SC2016
  get_sub2_cmds='''
    printf "%s" "${conoha_main_method_content}" \
      | grep -Eo "^( {4}| {8})[^ ]+ *)" \
      | grep -Ev "^ {4}(subcmds|\*)|^ {8}subcmds" \
      | tr -d "\n" \
      | sed "s/.* \(${sub_command} *)[^\*]*\).*/\1/g; s/^${sub_command} *)//g; s/ *//g; s/)/ /g; s/ *$//g"
  '''

  case "${sub_command}" in
    subcmds)
      # grep '^    [^ ]*)[ ]*$' ./conoha | grep -v subcmds | tr '\n' ' ' | sed 's/[ \*]//g; s/)/ /g; s/|/ /;'
      #echo "configure flavor image port servers sg securitygroup subnet tools"
      eval "${get_sub_cmds}" ;;
    completion)
      case "${sub2_command}" in
        subcmds) true ;;
        *      ) echo ". $(cd "$(dirname "$0")"; pwd)/$(basename -- "$0")" ;;
      esac ;;
    configure)
      case "${sub2_command}" in
        subcmds) true ;;
        *      ) ConoHaConfigure "$@" ;;
      esac ;;
    flavors)
      case "${sub2_command}" in
        subcmds     ) eval "${get_sub2_cmds}" ;;
        list        ) ConoHaFlavorsList "$@" ;;
        list-sumally) ConoHaFlavorsListSumally "$@" ;;
        *           ) PrintStderr "allowed value: $(bash "$0" "${sub_command}" subcmds | sed 's/^/ /; s/ /\\n  - /g')"; return 1 ;;
      esac ;;
    images)
      case "${sub2_command}" in
        subcmds     ) eval "${get_sub2_cmds}" ;;
        list        ) ConoHaImagesList "$@" ;;
        list-sumally) ConoHaImagesListSumally "$@" ;;
        *           ) PrintStderr "allowed value: $(bash "$0" "${sub_command}" subcmds | sed 's/^/ /; s/ /\\n  - /g')"; return 1 ;;
      esac ;;
    kubernetes)
      case "${sub2_command}" in
        subcmds                     ) eval "${get_sub2_cmds}" ;;
        create-cluster-single-master) ConoHaKubernetesCreateClusterSingleMaster "$@" ;;
        list-clusters               ) ConoHaKubernetesListClusters "$@" ;;
        list-clusters-json          ) ConoHaKubernetesListClustersJSON "$@" ;;
        list-cluster-nodes          ) ConoHaKubernetesListClusterNodes "$@" ;;
        list-cluster-nodes-json     ) ConoHaKubernetesListClusterNodesJSON "$@" ;;
        terminate-cluster           ) ConoHaKubernetesTerminateCluster "$@" ;;
        *                           ) PrintStderr "allowed value: $(bash "$0" "${sub_command}" subcmds | sed 's/^/ /; s/ /\\n  - /g')"; return 1 ;;
      esac ;;
    keypairs)
      case "${sub2_command}" in
        subcmds) eval "${get_sub2_cmds}" ;;
        list   ) ConoHaKeypairsList "$@" ;;
        upload ) ConoHaKeypairsUpload "$@" ;;
        *      ) PrintStderr "allowed value: $(bash "$0" "${sub_command}" subcmds | sed 's/^/ /; s/ /\\n  - /g')"; return 1 ;;
      esac ;;
    networks)
      case "${sub2_command}" in
        subcmds             ) eval "${get_sub2_cmds}" ;;
        create-local-network) ConoHaNetworksCreateLocalNetwork "$@" ;;
        delete              ) ConoHaNetworksDelete "$@" ;;
        list-local-networks ) ConoHaNetworksListLocalNetworks "$@" ;;
        *                   ) PrintStderr "allowed value: $(bash "$0" "${sub_command}" subcmds | sed 's/^/ /; s/ /\\n  - /g')"; return 1 ;;
      esac ;;
    ports)
      case "${sub2_command}" in
        subcmds     ) eval "${get_sub2_cmds}" ;;
        create      ) ConoHaPortsCreate "$@" ;;
        delete      ) ConoHaPortsDelete "$@" ;;
        list        ) ConoHaPortsList "$@" ;;
        list-sumally) ConoHaPortsListSumally "$@" ;;
        *           ) PrintStderr "allowed value: $(bash "$0" "${sub_command}" subcmds | sed 's/^/ /; s/ /\\n  - /g')"; return 1 ;;
      esac ;;
    securitygroups)
      case "${sub2_command}" in
        subcmds     ) eval "${get_sub2_cmds}" ;;
        list        ) ConoHaSecurityGroupsList "$@" ;;
        list-sumally) ConoHaSecurityGroupsListSumally "$@" ;;
        *           ) PrintStderr "allowed value: $(bash "$0" "${sub_command}" subcmds | sed 's/^/ /; s/ /\\n  - /g')"; return 1 ;;
      esac ;;
    servers)
      case "${sub2_command}" in
        subcmds            ) eval "${get_sub2_cmds}" ;;
        attach-port        ) ConoHaServersAttachPort "$@" ;;
        create             ) ConoHaServersCreate "$@" ;;
        delete             ) ConoHaServersDeleteWithConfirm "$@" ;;
        list-attached-ports) ConoHaServersListAttachedPorts "$@" ;;
        list               ) ConoHaServersList "$@" ;;
        list-detail        ) ConoHaServersListDetail "$@" ;;
        list-detail-sumally) ConoHaServersListDetailSumally "$@" ;;
        start              ) ConoHaServersStart "$@" ;;
        stop               ) ConoHaServersStop "$@" ;;
        *                  ) PrintStderr "allowed value: $(bash "$0" "${sub_command}" subcmds | sed 's/^/ /; s/ /\\n  - /g')"; return 1 ;;
      esac ;;
    subnets)
      case "${sub2_command}" in
        subcmds                    ) eval "${get_sub2_cmds}" ;;
        create-local-subnet        ) ConoHaSubnetsCreateLocalSubnet "$@" ;;
        delete                     ) ConoHaSubnetsDelete "$@" ;;
        list                       ) ConoHaSubnetsList "$@" ;;
        list-additional-ipaddresses) ConoHaSubnetsListAdditionalIPAddresses "$@" ;;
        list-local-subnets         ) ConoHaSubnetsListLocalSubnets "$@" ;;
        *                          ) PrintStderr "allowed value: $(bash "$0" "${sub_command}" subcmds | sed 's/^/ /; s/ /\\n  - /g')"; return 1 ;;
      esac ;;
    tools)
      case "${sub2_command}" in
        subcmds             ) eval "${get_sub2_cmds}" ;;
        get-image-ubuntu1804) ConoHaToolsGetImageUbuntu1804 "$@" ;;
        get-flavor-512mb    ) ConoHaToolsGetFlavor512MB "$@" ;;
        get-flavor-1gb      ) ConoHaToolsGetFlavor1GB "$@" ;;
        *                   ) PrintStderr "allowed value: $(bash "$0" "${sub_command}" subcmds | sed 's/^/ /; s/ /\\n  - /g')"; return 1 ;;
      esac ;;
    version)
      case "${sub2_command}" in
        subcmds) true ;;
        *      ) echo "${CONOHA_PROGRAM_NAME} ${CONOHA_VERSION}" ;;
      esac ;;
    *)
      PrintStderr "allowed value: $(bash "$0" subcmds | sed 's/^/ /; s/ /\\n  - /g')"; return 1 ;;
  esac
} && ConohaMain "$@"  ## main end DO NOT REMOVE ##

# -- Non Interactive ----------------
else
# -- Interactive ----------------


##
# conoha command as bash-completion
#
# The following function is for bash-completion.
# When executing script as a command,
# the following function is not defined nor executed.
#
# shellcheck disable=SC2016,SC2034,SC2039
##
__complete_conoha() {
  local cur prev cword
  _get_comp_words_by_ref -n : cur prev cword
  if [ "${cword}" -eq 1 ]; then
    eval 'COMPREPLY=( $(compgen -W "'"$(conoha subcmds)"'" -- "${cur}") )'
  elif [ "${cword}" -eq 2 ]; then
    eval 'COMPREPLY=( $(compgen -W "'"$(conoha "${prev}" subcmds)"'" -- "${cur}") )'
  fi
}
# shellcheck disable=SC2039
{ ! command -v complete 1>/dev/null; } || complete -F __complete_conoha conoha

# -- Interactive ----------------
fi
